config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users

  root :to =>"homes#top"
  get "home/about"=>"homes#about"

  resources :books do
    resources :book_comments, only: [:create,:destroy]
    resources :favorites, only: [:create,:destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create,:destroy]
    get 'follows' => 'relationships#follower', as: 'follows'
    get 'followers' => 'relationships#followed', as: 'followers'
  end

  resources :messages, only: [:show, :create]
  
  get '/search', to: 'searches#search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites,dependent: :destroy
  has_many :book_comments,dependent: :destroy
  has_many :week_favorites, -> { where(created_at: ((Time.current.at_end_of_day - 6.day).at_beginning_of_day)..(Time.current.at_end_of_day)) }, class_name: 'Favorite'
  has_many :browsings,dependent: :destroy


  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}

  def favorited?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.search_for(content,method)
    if method == 'perfect'
      Book.where(title: content)
    elsif method == 'forward'
      Book.where('title LIKE ?',content+'%')
    elsif method == 'backward'
      Book.where('title LIKE ?', '%'+content)
    else
      Book.where('title LIKE ?', '%' +content+'%')
    end
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  validates :comment, presence: true

  belongs_to :user
  belongs_to :book
end

app/models/browsing.rb
class Browsing < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/favorite.rb
class Favorite < ApplicationRecord

belongs_to :user
belongs_to :book

end

app/models/message.rb
class Message < ApplicationRecord

  validates :message,presence: true , length: {maximum: 140}

  belongs_to :user
  belongs_to :message_room
  
end

app/models/message_room.rb
class MessageRoom < ApplicationRecord

  has_many :users_rooms
  has_many :messages

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy 
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy 
  has_many :following_user, through: :follower, source: :followed 
  has_many :follower_user, through: :followed, source: :follower


  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_one_attached :profile_image
  has_many :users_rooms
  has_many :messages
  has_many :message_rooms
  has_many :browsings, dependent: :destroy


  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: {maximum: 50}

  
  
  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_user.include?(user)
  end

  def self.search_for(content,method)
    if method == 'perfect'
      User.where(title: content)
    elsif method == 'forward'
      User.where('name LIKE ?',content+'%')
    elsif method == 'backward'
      User.where('name LIKE ?', '%'+content)
    else
      User.where('name LIKE ?', '%' +content+'%')
    end
  end
end

app/models/users_room.rb
class UsersRoom < ApplicationRecord

  belongs_to :user
  belongs_to :message_room
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, only: [:index,:show]
  before_action :ensure_correct_user, only: [:edit,:update,:destroy]

  def show
    @book = Book.find(params[:id])
    unless Browsing.find_by(user_id: current_user.id, book_id: @book.id)
      current_user.browsings.create(book_id: @book.id)
    end
    @user = @book.user
    @new_book = Book.new
    @book_comment = BookComment.new
  end

  def index
    @books = Book.left_joins(:week_favorites).group(:id).order(Arel.sql('count(book_id) desc'))
    @book = Book.new
    @new_book = Book.new
    @user = User.find_by(id: current_user.id)
  end
  

  def create
    @book = Book.new(book_params)
    @user = @book.user
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    book = Book.find(params[:id])
    if book.update(book_params)
      redirect_to book_path(book.id), notice: "You have updated book successfully."
    else
      render :index
    end
  end

  def destroy
    book = Book.find(params[:id])
    if book.destroy
      redirect_to books_path
    end
  end

  private

  def book_params
    params.require(:book).permit(:title,:body).merge(user_id: current_user.id)
  end

  def ensure_correct_user
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to root_path
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :only_follow, only: [:show]

  def show
    @user = User.find(params[:id])
    message_rooms = current_user.users_rooms.pluck(:message_room_id)
    users_rooms = UsersRoom.find_by(user_id: @user.id,message_room_id: message_rooms)

    unless users_rooms.nil?
      @room = users_rooms.message_room
    else
      @room = MessageRoom.new
      @room.save
      UsersRoom.create(user_id: current_user.id, message_room_id: @room.id)
      UsersRoom.create(user_id:@user.id,message_room_id: @room.id)
    end
    @messages = @room.messages
    @message = Message.new(message_room_id: @room.id)
  end

  def create
    @message = current_user.messages.new(message_params)
    @message.save
    redirect_to request.referer
  end

  private

  def message_params
    params.require(:message).permit(:message,:message_room_id)
  end

  def only_follow
    user = User.find(params[:id])
    unless current_user.following?(user) 
      redirect_to books_path
    end
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update,:edit]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @new_book = Book.new
  end

  def index
    @users = User.all
    @user = User.find_by(id: current_user.id)
    @book = Book.new
    @new_book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_commentform.html.erb
          <% @book.book_comments.each do |bc| %>

          <div style="margin:1.5rem;">

              <%book_comment_user = bc.user%>
              <%= link_to user_path(book_comment_user), class: "bco" do %>
                <%=image_tag book_comment_user.get_profile_image,size:'100x100'%>
                <%=book_comment_user.name%>
              <%end%>

              <%=bc.comment%>
              <%if current_user == book_comment_user %>
                <%= link_to '削除',book_book_comment_path(bc.book_id, bc.id), class: "bc-d", method: :delete %>
              <% end %>

          </div>

          <%end%>
          
          <%= form_with model:[@book,@book_comment],local: true do |f| %>
            <div class="form-group">
              <%= f.label :comment %>
              <%= f.text_area :comment, class: 'form-control book_title' %>
            </div>
            <div class="form-group">
              <%= f.submit :送信,class:"sub"  %>
            </div>
          <% end %>

app/views/books/_form.html.erb
<%= form_with model:@new_book,url: books_path,local: true do |f| %>
<%= render 'layouts/errors', model: f.object %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= link_to(book.user) do %>
          <%= image_tag book.user.get_profile_image, size:'50x50' %>
          <% end %>
        </td>
        <td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
        <!--いいねされているかされていないかで分岐--->
        <!--レコード一致=いいね削除--->
        <%if book.favorited?(current_user)%>
          <td>
             <%=link_to "/books/book_id/favorites/id",method: :delete do%>
              <i class="fa-solid fa-heart" style="color:red;"></i><span class="good_count1" style="color:red;"><%=book.favorites.count %></span>
             <%end%>
          </td>
          <!--レコード不一致=いいねcreate--->
          <%else%>
          <td>
             <%=link_to "/books/#{book.id}/favorites",method: :post do%>
              <i class="fa-solid fa-heart" style="color:lightgray;"></i><span class="good_count2" style="color:lightgray;"><%= book.favorites.count %></span>
             <%end%>
          </td>
       <%end%>
        <!--良いねされているかされていないかで分岐--->

        <td>コメント数：<span class="comment_count"><%=book.book_comments.count%></span></td>
        <td>閲覧数：<span class="comment_count"><%= book.browsings.count %></span></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', @book, class: "book_#{@book.id}" %>
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'index', books: @books%>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info' %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form',book: @new_book %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
          <td><%= link_to(@book.user) do %>
            <%= image_tag @book.user.get_profile_image, size:"100x100" %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>
          <!--いいねされているかされていないかで分岐--->
          <!--レコード一致=いいね削除--->
          <%if @book.favorited?(current_user)%>
            <td>
             <%=link_to "/books/#{@book.id}/favorites/id",method: :delete do%>
                <i class="fa-solid fa-heart" style="color:red;"></i><span class="good_count1" style="color:red;"><%=@book.favorites.count %></span>
             <%end%>
            </td>
            <!--レコード不一致=いいねcreate--->
            <%else%>
            <td>
              <%=link_to "/books/#{@book.id}/favorites",method: :post do%>
                <i class="fa-solid fa-heart" style="color:lightgray;"></i><span class="good_count2" style="color:lightgray;"><%= @book.favorites.count %></span>
              <%end%>
            </td>
          <%end%>
          <!--良いねされているかされていないかで分岐--->
          <td>コメント数：<span class="comment_count"><%= @book.book_comments.count%></span></td>
          <td>閲覧数：<span class="comment_count"><%= @book.browsings.count %></span></td>
          <%if @book.user == current_user%>
            <td><%= link_to 'Edit', edit_book_path(@book.id), class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
            <td><%= link_to 'Destroy', book_path(@book.id), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%></td>
          <%end%>
        </tr>
        
      </table>
     <%= render 'books/commentform', book: @book,book_comment: @book_comment%>

    </div>
  </div>
</div>

app/views/messages/show.html.erb
<h1 id="message_room"><%= @user.name %> さんとのメッセージ</h1>

<div class="message_content">
  <% @messages.each do |m| %>
    <% if m.user_id == current_user.id %>
      <p><%= m.message %></p>
    <% else %>
      <p><%= m.message %></p>
    <% end %>
  <% end %>
</div>

<%= form_with model: @message do |f| %>
  <%= f.text_field :message %>
  <%= f.hidden_field :message_room_id %>
  <%= f.submit "送信"%>
<% end %>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>フォロー中：<%= user.follower.count %></td>
        <td>フォロワー：<%= user.followed.count %></td>
        <td>
          <% if current_user != user %>
            <% if current_user.following?(user) %>
              <%= link_to 'アンフォロー', user_relationships_path(user.id), method: :delete %>
            <% else %>
              <%= link_to 'フォロー', user_relationships_path(user.id), method: :post %>
            <% end %>
          <% end %>
        </td>
        <td><%= link_to 'Show',user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr>
    <%if @user.profile_image.attached?%>
      <%= image_tag @user.profile_image, size:'100x100' %>
    <% else %>
      <%= image_tag "no_image.jpg", size:'100x100', style:"margin:1rem;"%>
    <%end%>
  </tr>
  <tr>
	  <th>name</th>
	  <th><%= @user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= @user.introduction %></th>
  </tr>
  <tr>
	  <th>フォロー中</th>
	  <th><%= link_to @user.follower.count, user_follows_path(@user) %></th>
  </tr>
  <tr>
	  <th>フォロワー</th>
	  <th><%= link_to @user.followed.count, user_followers_path(@user) %></th>
  </tr>
</table>

<div class='row'>
  <%if current_user != @user%>
    <%if current_user.following?(@user)%>
      <%= link_to "アンフォロー" , user_relationships_path(@user.id), method: :delete, class:"fo-btn"%>
    <%else%>
      <%= link_to "フォロー" ,user_relationships_path(@user.id), method: :post, class:"fo-btn"%>
    <%end%>
  <%end%>
</div>

<div>
  <% if current_user != @user && current_user.following?(@user)%>
    <%= link_to 'chatを始める', message_path(@user.id)%>
  <%end%>
</div>

  <%= link_to edit_user_path(@user), class: "btn btn-outline-secondary btn-block edit_user_#{@user.id}" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
    <%= render 'layouts/errors', model: f.object %>

     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<h2>User info</h2>
<%= render 'info', user: @user%>

<h2 class="mt-3">New book</h2>
<%= render 'books/form', book: @book %>

<h2>Users</h2>
<%= render 'index',users: @users %>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>